// Built-in/reserved CLIPS functions, organized to match the categories used
// by the CLIPS Basic Programming Guide (v6.4.2) chapter on predefined
// system functions. Each entry's description is a concise, one-sentence
// summary of that function's documented behavior — not verbatim manual
// text, but consistent with it.
//
// Sourced from bpg642.pdf (in the repository root) — Section 12 ("Actions
// and Functions") for behavior/syntax, cross-checked against Appendix H
// ("Reserved Function Names") for completeness. Appendix H's own table
// omits a handful of names that Section 12 documents (e.g. test, exists,
// forall, sort, case, default) — those are included here since they're
// real. A few appendix names are cross-referenced from Volume II (the
// Advanced Programming Guide, not included in this repo) rather than
// bpg642.pdf directly (e.g. show-fht, show-fpn, show-joins, show-opn,
// primitives-info, rule-complexity, str-assert); their descriptions are
// best-effort based on naming convention and cross-references within
// bpg642.pdf, not a direct manual quote.

const CATEGORIES = {
  ARITHMETIC: 'arithmetic',
  COMPARISON: 'comparison',
  LOGICAL: 'logical',
  PREDICATE: 'predicate',
  STRING: 'string',
  MULTIFIELD: 'multifield',
  IO: 'io',
  FLOW_CONTROL: 'flow-control',
  FACT: 'fact',
  MISC: 'misc'
};

const BUILTINS = [
  // --- Arithmetic ---
  { name: '-', category: CATEGORIES.ARITHMETIC, syntax: '(- <number> <number>+)', description: 'Subtracts each subsequent number from the first.' },
  { name: '*', category: CATEGORIES.ARITHMETIC, syntax: '(* <number> <number>+)', description: 'Returns the product of two or more numbers.' },
  { name: '**', category: CATEGORIES.ARITHMETIC, syntax: '(** <number> <number>)', description: 'Returns the first number raised to the power of the second.' },
  { name: '/', category: CATEGORIES.ARITHMETIC, syntax: '(/ <number> <number>+)', description: 'Divides the first number by each subsequent number.' },
  { name: '+', category: CATEGORIES.ARITHMETIC, syntax: '(+ <number> <number>+)', description: 'Returns the sum of two or more numbers.' },
  { name: 'abs', category: CATEGORIES.ARITHMETIC, syntax: '(abs <number>)', description: 'Returns the absolute value of a number.' },
  { name: 'acos', category: CATEGORIES.ARITHMETIC, syntax: '(acos <number>)', description: 'Returns the arccosine, in radians, of a number.' },
  { name: 'acosh', category: CATEGORIES.ARITHMETIC, syntax: '(acosh <number>)', description: 'Returns the inverse hyperbolic cosine of a number.' },
  { name: 'acot', category: CATEGORIES.ARITHMETIC, syntax: '(acot <number>)', description: 'Returns the arccotangent, in radians, of a number.' },
  { name: 'acoth', category: CATEGORIES.ARITHMETIC, syntax: '(acoth <number>)', description: 'Returns the inverse hyperbolic cotangent of a number.' },
  { name: 'acsc', category: CATEGORIES.ARITHMETIC, syntax: '(acsc <number>)', description: 'Returns the arccosecant, in radians, of a number.' },
  { name: 'acsch', category: CATEGORIES.ARITHMETIC, syntax: '(acsch <number>)', description: 'Returns the inverse hyperbolic cosecant of a number.' },
  { name: 'asec', category: CATEGORIES.ARITHMETIC, syntax: '(asec <number>)', description: 'Returns the arcsecant, in radians, of a number.' },
  { name: 'asech', category: CATEGORIES.ARITHMETIC, syntax: '(asech <number>)', description: 'Returns the inverse hyperbolic secant of a number.' },
  { name: 'asin', category: CATEGORIES.ARITHMETIC, syntax: '(asin <number>)', description: 'Returns the arcsine, in radians, of a number.' },
  { name: 'asinh', category: CATEGORIES.ARITHMETIC, syntax: '(asinh <number>)', description: 'Returns the inverse hyperbolic sine of a number.' },
  { name: 'atan', category: CATEGORIES.ARITHMETIC, syntax: '(atan <number>)', description: 'Returns the arctangent, in radians, of a number.' },
  { name: 'atan2', category: CATEGORIES.ARITHMETIC, syntax: '(atan2 <number> <number>)', description: 'Returns the arctangent, in radians, of the first number divided by the second.' },
  { name: 'atanh', category: CATEGORIES.ARITHMETIC, syntax: '(atanh <number>)', description: 'Returns the inverse hyperbolic tangent of a number.' },
  { name: 'cos', category: CATEGORIES.ARITHMETIC, syntax: '(cos <number>)', description: 'Returns the cosine of an angle given in radians.' },
  { name: 'cosh', category: CATEGORIES.ARITHMETIC, syntax: '(cosh <number>)', description: 'Returns the hyperbolic cosine of a number.' },
  { name: 'cot', category: CATEGORIES.ARITHMETIC, syntax: '(cot <number>)', description: 'Returns the cotangent of an angle given in radians.' },
  { name: 'coth', category: CATEGORIES.ARITHMETIC, syntax: '(coth <number>)', description: 'Returns the hyperbolic cotangent of a number.' },
  { name: 'csc', category: CATEGORIES.ARITHMETIC, syntax: '(csc <number>)', description: 'Returns the cosecant of an angle given in radians.' },
  { name: 'csch', category: CATEGORIES.ARITHMETIC, syntax: '(csch <number>)', description: 'Returns the hyperbolic cosecant of a number.' },
  { name: 'deg-grad', category: CATEGORIES.ARITHMETIC, syntax: '(deg-grad <number>)', description: 'Converts an angle in degrees to gradians.' },
  { name: 'deg-rad', category: CATEGORIES.ARITHMETIC, syntax: '(deg-rad <number>)', description: 'Converts an angle in degrees to radians.' },
  { name: 'div', category: CATEGORIES.ARITHMETIC, syntax: '(div <number> <number>+)', description: 'Performs integer division, truncating any remainder.' },
  { name: 'exp', category: CATEGORIES.ARITHMETIC, syntax: '(exp <number>)', description: 'Returns e raised to the power of the argument.' },
  { name: 'float', category: CATEGORIES.ARITHMETIC, syntax: '(float <number>)', description: 'Converts a number to a floating-point value.' },
  { name: 'grad-deg', category: CATEGORIES.ARITHMETIC, syntax: '(grad-deg <number>)', description: 'Converts an angle in gradians to degrees.' },
  { name: 'integer', category: CATEGORIES.ARITHMETIC, syntax: '(integer <number>)', description: 'Converts a number to an integer by truncating any fractional part.' },
  { name: 'log', category: CATEGORIES.ARITHMETIC, syntax: '(log <number>)', description: 'Returns the natural logarithm of a number.' },
  { name: 'log10', category: CATEGORIES.ARITHMETIC, syntax: '(log10 <number>)', description: 'Returns the base-10 logarithm of a number.' },
  { name: 'max', category: CATEGORIES.ARITHMETIC, syntax: '(max <number>+)', description: 'Returns the largest of one or more numbers.' },
  { name: 'min', category: CATEGORIES.ARITHMETIC, syntax: '(min <number>+)', description: 'Returns the smallest of one or more numbers.' },
  { name: 'mod', category: CATEGORIES.ARITHMETIC, syntax: '(mod <number> <number>)', description: 'Returns the remainder of dividing the first number by the second.' },
  { name: 'pi', category: CATEGORIES.ARITHMETIC, syntax: '(pi)', description: 'Returns the value of π.' },
  { name: 'rad-deg', category: CATEGORIES.ARITHMETIC, syntax: '(rad-deg <number>)', description: 'Converts an angle in radians to degrees.' },
  { name: 'round', category: CATEGORIES.ARITHMETIC, syntax: '(round <number>)', description: 'Rounds a number to the nearest integer.' },
  { name: 'sec', category: CATEGORIES.ARITHMETIC, syntax: '(sec <number>)', description: 'Returns the secant of an angle given in radians.' },
  { name: 'sech', category: CATEGORIES.ARITHMETIC, syntax: '(sech <number>)', description: 'Returns the hyperbolic secant of a number.' },
  { name: 'sin', category: CATEGORIES.ARITHMETIC, syntax: '(sin <number>)', description: 'Returns the sine of an angle given in radians.' },
  { name: 'sinh', category: CATEGORIES.ARITHMETIC, syntax: '(sinh <number>)', description: 'Returns the hyperbolic sine of a number.' },
  { name: 'sqrt', category: CATEGORIES.ARITHMETIC, syntax: '(sqrt <number>)', description: 'Returns the square root of a number.' },
  { name: 'tan', category: CATEGORIES.ARITHMETIC, syntax: '(tan <number>)', description: 'Returns the tangent of an angle given in radians.' },
  { name: 'tanh', category: CATEGORIES.ARITHMETIC, syntax: '(tanh <number>)', description: 'Returns the hyperbolic tangent of a number.' },

  // --- Comparison ---
  { name: '<', category: CATEGORIES.COMPARISON, syntax: '(< <number> <number>+)', description: 'Returns TRUE if each numeric argument is less than the one that follows it.' },
  { name: '<=', category: CATEGORIES.COMPARISON, syntax: '(<= <number> <number>+)', description: 'Returns TRUE if each numeric argument is less than or equal to the one that follows it.' },
  { name: '<>', category: CATEGORIES.COMPARISON, syntax: '(<> <number> <number>+)', description: 'Returns TRUE if all of its numeric arguments are different.' },
  { name: '=', category: CATEGORIES.COMPARISON, syntax: '(= <number> <number>+)', description: 'Returns TRUE if all of its numeric arguments are equal.' },
  { name: '>', category: CATEGORIES.COMPARISON, syntax: '(> <number> <number>+)', description: 'Returns TRUE if each numeric argument is greater than the one that follows it.' },
  { name: '>=', category: CATEGORIES.COMPARISON, syntax: '(>= <number> <number>+)', description: 'Returns TRUE if each numeric argument is greater than or equal to the one that follows it.' },
  { name: 'eq', category: CATEGORIES.COMPARISON, syntax: '(eq <expression> <expression>+)', description: 'Returns TRUE if all of its arguments are identical in both type and value.' },
  { name: 'neq', category: CATEGORIES.COMPARISON, syntax: '(neq <expression> <expression>+)', description: 'Returns TRUE if any two of its arguments differ in type or value.' },

  // --- Logical ---
  { name: 'and', category: CATEGORIES.LOGICAL, syntax: '(and <expression>+)', description: 'Returns TRUE if all of its arguments evaluate to a non-FALSE value.' },
  { name: 'exists', category: CATEGORIES.LOGICAL, syntax: '(exists <conditional-element>+)', description: 'A conditional element that is satisfied if at least one match exists for the given patterns.' },
  { name: 'forall', category: CATEGORIES.LOGICAL, syntax: '(forall <conditional-element> <conditional-element>+)', description: 'A conditional element that is satisfied if every match of the first pattern also satisfies the remaining patterns.' },
  { name: 'logical', category: CATEGORIES.LOGICAL, syntax: '(logical <conditional-element>+)', description: 'Marks patterns whose matching facts become logical dependencies of any facts asserted on the rule\'s right-hand side.' },
  { name: 'not', category: CATEGORIES.LOGICAL, syntax: '(not <expression>)', description: 'Returns TRUE if its argument evaluates to FALSE, and FALSE otherwise.' },
  { name: 'or', category: CATEGORIES.LOGICAL, syntax: '(or <expression>+)', description: 'Returns TRUE if any of its arguments evaluate to a non-FALSE value.' },
  { name: 'test', category: CATEGORIES.LOGICAL, syntax: '(test <expression>)', description: 'A conditional element that matches only if the expression evaluates to a non-FALSE value.' },

  // --- Predicate / type-check ---
  { name: 'evenp', category: CATEGORIES.PREDICATE, syntax: '(evenp <integer>)', description: 'Returns TRUE for even numbers.' },
  { name: 'external-addressp', category: CATEGORIES.PREDICATE, syntax: '(external-addressp <expression>)', description: 'Returns TRUE for external addresses (the modern replacement for the deprecated pointerp).' },
  { name: 'floatp', category: CATEGORIES.PREDICATE, syntax: '(floatp <expression>)', description: 'Returns TRUE for floats.' },
  { name: 'instance-addressp', category: CATEGORIES.PREDICATE, syntax: '(instance-addressp <expression>)', description: 'Returns TRUE for instance addresses.' },
  { name: 'instance-namep', category: CATEGORIES.PREDICATE, syntax: '(instance-namep <expression>)', description: 'Returns TRUE for instance names.' },
  { name: 'instancep', category: CATEGORIES.PREDICATE, syntax: '(instancep <expression>)', description: 'Returns TRUE for instance addresses.' },
  { name: 'integerp', category: CATEGORIES.PREDICATE, syntax: '(integerp <expression>)', description: 'Returns TRUE for integers.' },
  { name: 'lexemep', category: CATEGORIES.PREDICATE, syntax: '(lexemep <expression>)', description: 'Returns TRUE for symbols and strings.' },
  { name: 'multifieldp', category: CATEGORIES.PREDICATE, syntax: '(multifieldp <expression>)', description: 'Returns TRUE for multifield values.' },
  { name: 'next-handlerp', category: CATEGORIES.PREDICATE, syntax: '(next-handlerp)', description: 'Returns the symbol TRUE if there is another message-handler available for execution; otherwise, it returns the symbol FALSE.' },
  { name: 'next-methodp', category: CATEGORIES.PREDICATE, syntax: '(next-methodp)', description: 'Returns TRUE if a shadowed method exists that can be called with call-next-method from within the current method.' },
  { name: 'numberp', category: CATEGORIES.PREDICATE, syntax: '(numberp <expression>)', description: 'Returns TRUE for integers and floats.' },
  { name: 'oddp', category: CATEGORIES.PREDICATE, syntax: '(oddp <integer>)', description: 'Returns TRUE for odd numbers.' },
  { name: 'pointerp', category: CATEGORIES.PREDICATE, syntax: '(pointerp <expression>)', description: 'Deprecated: returns TRUE for external addresses; use external-addressp instead.' },
  { name: 'stringp', category: CATEGORIES.PREDICATE, syntax: '(stringp <expression>)', description: 'Returns TRUE for strings.' },
  { name: 'symbolp', category: CATEGORIES.PREDICATE, syntax: '(symbolp <expression>)', description: 'Returns TRUE for symbols.' },

  // --- String ---
  { name: 'assert-string', category: CATEGORIES.STRING, syntax: '(assert-string <string-expression>)', description: 'Is similar to the assert function in that it creates a new fact and adds it to the fact-list.' },
  { name: 'lowcase', category: CATEGORIES.STRING, syntax: '(lowcase <string-or-symbol>)', description: 'Converts all uppercase characters in a string or symbol to lowercase.' },
  { name: 'str-cat', category: CATEGORIES.STRING, syntax: '(str-cat <expression>+)', description: 'Concatenates its arguments together into a single string.' },
  { name: 'str-compare', category: CATEGORIES.STRING, syntax: '(str-compare <string-1> <string-2> [<max-length>])', description: 'Compares two strings or symbols character by character, returning a negative, zero, or positive integer.' },
  { name: 'str-index', category: CATEGORIES.STRING, syntax: '(str-index <substring> <string>)', description: 'Returns the starting position of the first occurrence of a substring within a string, or FALSE if not found.' },
  { name: 'str-length', category: CATEGORIES.STRING, syntax: '(str-length <string>)', description: 'Returns the number of characters in a string or symbol.' },
  { name: 'string-to-field', category: CATEGORIES.STRING, syntax: '(string-to-field <string>)', description: 'Parses a string and returns the single field value (symbol, string, or number) it represents.' },
  { name: 'sub-string', category: CATEGORIES.STRING, syntax: '(sub-string <begin> <end> <string>)', description: 'Returns the substring between the given start and end character positions.' },
  { name: 'sym-cat', category: CATEGORIES.STRING, syntax: '(sym-cat <expression>+)', description: 'Concatenates its arguments together into a single symbol.' },
  { name: 'upcase', category: CATEGORIES.STRING, syntax: '(upcase <string-or-symbol>)', description: 'Converts all lowercase characters in a string or symbol to uppercase.' },

  // --- Multifield ---
  { name: 'create$', category: CATEGORIES.MULTIFIELD, syntax: '(create$ <expression>*)', description: 'Appends its arguments together to create a new multifield value.' },
  { name: 'delete-member$', category: CATEGORIES.MULTIFIELD, syntax: '(delete-member$ <multifield-expression> <value-or-multifield>+)', description: 'Returns a copy of a multifield value with all fields matching the given value(s) removed.' },
  { name: 'delete$', category: CATEGORIES.MULTIFIELD, syntax: '(delete$ <multifield-expression> <begin> <end>)', description: 'Returns a copy of a multifield value with the fields between the given positions removed.' },
  { name: 'difference$', category: CATEGORIES.MULTIFIELD, syntax: '(difference$ <multifield-expression>+)', description: 'Creates a multifield value containing a single occurrence of each value that is contained within its first argument, but none of its subsequent multifield arguments.' },
  { name: 'expand$', category: CATEGORIES.MULTIFIELD, syntax: '$expand$<multifield-variable>$', description: 'Used within a function call argument list to expand a multifield variable into separate arguments.' },
  { name: 'explode$', category: CATEGORIES.MULTIFIELD, syntax: '(explode$ <string>)', description: 'Constructs a multifield value from a string, using each field in the string as a field of the result.' },
  { name: 'first$', category: CATEGORIES.MULTIFIELD, syntax: '(first$ <multifield-expression>)', description: 'Returns a one-field multifield value containing the first field of its argument.' },
  { name: 'implode$', category: CATEGORIES.MULTIFIELD, syntax: '(implode$ <multifield-expression>)', description: 'Constructs a string by concatenating the fields of a multifield value, separated by spaces.' },
  { name: 'insert$', category: CATEGORIES.MULTIFIELD, syntax: '(insert$ <multifield-expression> <index> <value>+)', description: 'Returns a copy of a multifield value with the given value(s) inserted at the specified position.' },
  { name: 'intersection$', category: CATEGORIES.MULTIFIELD, syntax: '(intersection$ <multifield-expression>*)', description: 'Creates a multifield value containing a single occurrence of each value that is contained within all of its multifield arguments.' },
  { name: 'length$', category: CATEGORIES.MULTIFIELD, syntax: '(length$ <multifield-expression>)', description: 'Returns the number of fields in a multifield value.' },
  { name: 'member$', category: CATEGORIES.MULTIFIELD, syntax: '(member$ <value> <multifield-expression>)', description: 'Returns the position of a value within a multifield value, or FALSE if it is not present.' },
  { name: 'nth$', category: CATEGORIES.MULTIFIELD, syntax: '(nth$ <index> <multifield-expression>)', description: 'Returns the field at the given position (1-based) of a multifield value.' },
  { name: 'replace-member$', category: CATEGORIES.MULTIFIELD, syntax: '(replace-member$ <multifield-expression> <replacement> <value-or-multifield>+)', description: 'Returns a copy of a multifield value with every field matching the given value(s) replaced.' },
  { name: 'replace$', category: CATEGORIES.MULTIFIELD, syntax: '(replace$ <multifield-expression> <begin> <end> <value>+)', description: 'Returns a copy of a multifield value with the fields between the given positions replaced by new value(s).' },
  { name: 'rest$', category: CATEGORIES.MULTIFIELD, syntax: '(rest$ <multifield-expression>)', description: 'Returns a multifield value containing all but the first field of its argument.' },
  { name: 'sort', category: CATEGORIES.MULTIFIELD, syntax: '(sort <comparison-function> <expression>*)', description: 'Sorts its arguments into a multifield value using the given comparison function.' },
  { name: 'subseq$', category: CATEGORIES.MULTIFIELD, syntax: '(subseq$ <multifield-expression> <begin> <end>)', description: 'Returns the fields of a multifield value between the given start and end positions, inclusive.' },
  { name: 'subsetp', category: CATEGORIES.MULTIFIELD, syntax: '(subsetp <multifield-1> <multifield-2>)', description: 'Returns TRUE if every field in the first multifield value is also present in the second.' },
  { name: 'union$', category: CATEGORIES.MULTIFIELD, syntax: '(union$ <multifield-expression>*)', description: 'Creates a multifield value containing a single occurrence of each value contained within each of its multifield arguments.' },

  // --- I/O ---
  { name: 'close', category: CATEGORIES.IO, syntax: '(close [<logical-name>])', description: 'Closes the file associated with the given logical name (or all open files, if none is given).' },
  { name: 'flush', category: CATEGORIES.IO, syntax: '(flush [<logical-name>])', description: 'Flushes buffered output for the given logical name (or all open files, if none is given).' },
  { name: 'format', category: CATEGORIES.IO, syntax: '(format <logical-name> <format-string> <expression>*)', description: 'Prints its arguments to the given logical name using printf-style format directives (e.g. ~n, ~d).' },
  { name: 'get-char', category: CATEGORIES.IO, syntax: '(get-char [<logical-name>])', description: 'Reads and returns a single character of input as its integer character code.' },
  { name: 'open', category: CATEGORIES.IO, syntax: '(open <file-name> <logical-name> [<mode>])', description: 'Opens a file and associates it with a logical name for subsequent I/O.' },
  { name: 'print', category: CATEGORIES.IO, syntax: '(print <expression>*)', description: 'A variant of printout that always sends output to stdout, without needing a logical name argument.' },
  { name: 'println', category: CATEGORIES.IO, syntax: '(println <expression>*)', description: 'Like print, but appends a newline (crlf) after printing its arguments.' },
  { name: 'printout', category: CATEGORIES.IO, syntax: '(printout <logical-name> <expression>*)', description: 'Prints each expression to the device attached to the given logical name (use t for standard output); crlf forces a newline.' },
  { name: 'read', category: CATEGORIES.IO, syntax: '(read [<logical-name>])', description: 'Reads and returns a single token (number, symbol, or string) from the given input source.' },
  { name: 'readline', category: CATEGORIES.IO, syntax: '(readline [<logical-name>])', description: 'Reads and returns an entire line of input as a string.' },
  { name: 'remove', category: CATEGORIES.IO, syntax: '(remove <file-name>)', description: 'Deletes the specified file from disk.' },
  { name: 'rename', category: CATEGORIES.IO, syntax: '(rename <old-file-name> <new-file-name>)', description: 'Renames a file on disk.' },
  { name: 'unget-char', category: CATEGORIES.IO, syntax: '(unget-char [<logical-name>] <character>)', description: 'Allows a single character to be returned to an input source.' },

  // --- Flow of control ---
  { name: 'bind', category: CATEGORIES.FLOW_CONTROL, syntax: '(bind <variable> <expression>*)', description: 'Assigns a value (or, given several expressions, a multifield value) to a variable and returns the value assigned.' },
  { name: 'break', category: CATEGORIES.FLOW_CONTROL, syntax: '(break)', description: 'Immediately exits the innermost enclosing loop (while, loop-for-count, or progn$).' },
  { name: 'case', category: CATEGORIES.FLOW_CONTROL, syntax: '(case <value> then <action>*)', description: 'A clause within switch whose actions run if its value matches the switch expression.' },
  { name: 'default', category: CATEGORIES.FLOW_CONTROL, syntax: '(default <action>*)', description: 'The clause within switch whose actions run when no case value matches.' },
  { name: 'foreach', category: CATEGORIES.FLOW_CONTROL, syntax: '(foreach <field-variable> <multifield-expression> <expression>*)', description: 'Performs a set of actions for each field of a multifield value.' },
  { name: 'halt', category: CATEGORIES.FLOW_CONTROL, syntax: '(halt)', description: 'Stops execution of activated rules.' },
  { name: 'if', category: CATEGORIES.FLOW_CONTROL, syntax: '(if <expression> then <action>* [else <action>*])', description: 'Evaluates the condition and executes the "then" actions if it is non-FALSE, otherwise the "else" actions.' },
  { name: 'loop-for-count', category: CATEGORIES.FLOW_CONTROL, syntax: '(loop-for-count (<var> [<start>] <end>) do <action>*)', description: 'Executes its actions once for each integer from the start value (default 1) to the end value.' },
  { name: 'object-pattern-match-delay', category: CATEGORIES.FLOW_CONTROL, syntax: '(object-pattern-match-delay <action>*)', description: 'Acts like progn, but delays any object pattern-matching side effects until all actions have executed.' },
  { name: 'progn', category: CATEGORIES.FLOW_CONTROL, syntax: '(progn <expression>*)', description: 'Evaluates each expression in sequence and returns the value of the last one.' },
  { name: 'progn$', category: CATEGORIES.FLOW_CONTROL, syntax: '(progn$ (<var> <multifield-expression>) <action>*)', description: 'Executes its actions once for each field of a multifield value, binding the field (and optionally its index) to a variable.' },
  { name: 'return', category: CATEGORIES.FLOW_CONTROL, syntax: '(return [<expression>])', description: 'Immediately exits the enclosing deffunction or procedural context, optionally returning a value.' },
  { name: 'switch', category: CATEGORIES.FLOW_CONTROL, syntax: '(switch <expression> (case <value> then <action>*)* [(default <action>*)])', description: 'Evaluates the expression and executes the actions of the first matching case (or the default, if none match).' },
  { name: 'while', category: CATEGORIES.FLOW_CONTROL, syntax: '(while <expression> do <action>*)', description: 'Repeatedly executes its actions as long as the condition evaluates to a non-FALSE value.' },

  // --- Fact / instance manipulation ---
  { name: 'active-duplicate-instance', category: CATEGORIES.FACT, syntax: '(active-duplicate-instance <instance> [to <instance-name>] <slot-override>*)', description: 'Uses the direct-duplicate message to change the values of the instance.' },
  { name: 'active-initialize-instance', category: CATEGORIES.FACT, syntax: '(active-initialize-instance <instance-name-expression> <slot-override>*)', description: 'Like initialize-instance, but does not delay object pattern-matching until all slot overrides are processed.' },
  { name: 'active-make-instance', category: CATEGORIES.FACT, syntax: '(active-make-instance <instance-definition>)', description: 'Like make-instance, but does not delay object pattern-matching until all slot overrides are processed.' },
  { name: 'active-message-duplicate-instance', category: CATEGORIES.FACT, syntax: '(active-message-duplicate-instance <instance> [to <instance-name>] <slot-override>*)', description: 'Uses the message-duplicate message to change the values of the instance.' },
  { name: 'active-message-modify-instance', category: CATEGORIES.FACT, syntax: '(active-message-modify-instance <instance> <slot-override>*)', description: 'Uses the message-modify message to change the values of the instance.' },
  { name: 'active-modify-instance', category: CATEGORIES.FACT, syntax: '(active-modify-instance <instance> <slot-override>*)', description: 'Uses the direct-modify message to change the values of the instance.' },
  { name: 'any-factp', category: CATEGORIES.FACT, syntax: '(any-factp <fact-set-template> <query>)', description: 'Returns TRUE if at least one fact-set matching the template satisfies the query.' },
  { name: 'any-instancep', category: CATEGORIES.FACT, syntax: '(any-instancep <instance-set-template> <query>)', description: 'Returns TRUE if at least one instance-set matching the template satisfies the query.' },
  { name: 'assert', category: CATEGORIES.FACT, syntax: '(assert <fact>+)', description: 'Adds one or more facts to the fact list.' },
  { name: 'bload-facts', category: CATEGORIES.FACT, syntax: '(bload-facts <file-name>)', description: 'Works exactly like load-facts except that it can only work with files generated by bsave-facts.' },
  { name: 'bload-instances', category: CATEGORIES.FACT, syntax: '(bload-instances <file-name>)', description: 'Is similar to restore-instances except that it can only work with files generated by bsave-instances.' },
  { name: 'bsave-instances', category: CATEGORIES.FACT, syntax: '(bsave-instances <file-name> [local | visible [[inherit] <class>+])', description: 'Works exactly like save-instances command except that the instances are saved in a binary format which can only be loaded with the bload-instances command.' },
  { name: 'deffacts-module', category: CATEGORIES.FACT, syntax: '(deffacts-module <deffacts-name>)', description: 'Returns the module in which the specified deffacts name is defined.' },
  { name: 'definstances-module', category: CATEGORIES.FACT, syntax: '(definstances-module <definstances-name>)', description: 'Returns the module in which the specified definstances name is defined.' },
  { name: 'delayed-do-for-all-facts', category: CATEGORIES.FACT, syntax: '(delayed-do-for-all-facts <fact-set-template> <query> <action>*)', description: 'Like do-for-all-facts, but delays fact pattern-matching side effects until all actions have executed.' },
  { name: 'delayed-do-for-all-instances', category: CATEGORIES.FACT, syntax: '(delayed-do-for-all-instances <instance-set-template> <query> <action>*)', description: 'Like do-for-all-instances, but delays object pattern-matching side effects until all actions have executed.' },
  { name: 'delete-instance', category: CATEGORIES.FACT, syntax: '(delete-instance)', description: 'Operates implicitly on the active instance for a message, and thus can only be called from within the body of a message-handler.' },
  { name: 'do-for-all-facts', category: CATEGORIES.FACT, syntax: '(do-for-all-facts <fact-set-template> <query> <action>*)', description: 'Executes actions once for every fact-set matching the template that satisfies the query.' },
  { name: 'do-for-all-instances', category: CATEGORIES.FACT, syntax: '(do-for-all-instances <instance-set-template> <query> <action>*)', description: 'Executes actions once for every instance-set matching the template that satisfies the query.' },
  { name: 'do-for-fact', category: CATEGORIES.FACT, syntax: '(do-for-fact <fact-set-template> <query> <action>*)', description: 'Executes actions once for the first fact-set matching the template that satisfies the query.' },
  { name: 'do-for-instance', category: CATEGORIES.FACT, syntax: '(do-for-instance <instance-set-template> <query> <action>*)', description: 'Executes actions once for the first instance-set matching the template that satisfies the query.' },
  { name: 'duplicate', category: CATEGORIES.FACT, syntax: '(duplicate <fact-index-or-address> (<slot-name> <value>*)*)', description: 'Asserts a copy of a deftemplate fact, optionally with some slot values changed.' },
  { name: 'duplicate-instance', category: CATEGORIES.FACT, syntax: '(duplicate-instance <instance> [(to <new-name>)] (<slot-name> <value>*)*)', description: 'Creates a new instance as a copy of an existing one, optionally with some slot values changed.' },
  { name: 'fact-existp', category: CATEGORIES.FACT, syntax: '(fact-existp <fact-address-or-index>)', description: 'Returns the symbol TRUE if the fact specified by its fact-index or fact- address argument exists; otherwise, the symbol FALSE is returned.' },
  { name: 'fact-index', category: CATEGORIES.FACT, syntax: '(fact-index <fact-address>)', description: 'Returns the fact-index (an integer) of a fact-address.' },
  { name: 'fact-relation', category: CATEGORIES.FACT, syntax: '(fact-relation <fact-address-or-index>)', description: 'Returns the deftemplate (relation) name associated with the fact.' },
  { name: 'fact-slot-names', category: CATEGORIES.FACT, syntax: '(fact-slot-names <fact-address-or-index>)', description: 'Returns a multifield value containing the slot names associated with a fact.' },
  { name: 'fact-slot-value', category: CATEGORIES.FACT, syntax: '(fact-slot-value <fact-address-or-index> <slot-name>)', description: 'Returns the value of the specified slot from the specified fact.' },
  { name: 'facts', category: CATEGORIES.FACT, syntax: '(facts [<module-name>] [<start> [<end> [<max>]]])', description: 'Lists existing facts, optionally filtered by module and fact-index range.' },
  { name: 'find-all-facts', category: CATEGORIES.FACT, syntax: '(find-all-facts <fact-set-template> <query>)', description: 'Returns a multifield value of the fact-addresses of every fact-set matching the template that satisfies the query.' },
  { name: 'find-all-instances', category: CATEGORIES.FACT, syntax: '(find-all-instances <instance-set-template> <query>)', description: 'Returns a multifield value of the addresses of every instance-set matching the template that satisfies the query.' },
  { name: 'find-fact', category: CATEGORIES.FACT, syntax: '(find-fact <fact-set-template> <query>)', description: 'Returns the fact-address of the first fact-set matching the template that satisfies the query, or FALSE.' },
  { name: 'find-instance', category: CATEGORIES.FACT, syntax: '(find-instance <instance-set-template> <query>)', description: 'Returns the address of the first instance-set matching the template that satisfies the query, or FALSE.' },
  { name: 'get-deffacts-list', category: CATEGORIES.FACT, syntax: '(get-deffacts-list [<module-name>])', description: 'Returns a multifield value containing the names of all deffacts constructs visible to the module specified by <module-name> or to the current module if none is specified.' },
  { name: 'get-definstances-list', category: CATEGORIES.FACT, syntax: '(get-definstances-list [<module-name>])', description: 'Returns a multifield value containing the names of all definstances constructs visible to the module specified by <module-name> or to the current module if none is specified.' },
  { name: 'get-fact-duplication', category: CATEGORIES.FACT, syntax: '(get-fact-duplication)', description: 'Returns the current value of the fact duplication behavior (the symbol TRUE or FALSE).' },
  { name: 'get-fact-list', category: CATEGORIES.FACT, syntax: '(get-fact-list [<module-name>])', description: 'Returns a multifield containing the list of facts visible to the module specified by <module-name> or to the current module if none is specified.' },
  { name: 'initialize-instance', category: CATEGORIES.FACT, syntax: '(initialize-instance <instance-name-expression> <slot-override>*)', description: 'Provides the ability to reinitialize an existing instance with class defaults and new slot-overrides.' },
  { name: 'instance-existp', category: CATEGORIES.FACT, syntax: '(instance-existp <instance-expression>)', description: 'Returns the symbol TRUE if the specified instance exists; otherwise, it returns the symbol FALSE.' },
  { name: 'instance-name-to-symbol', category: CATEGORIES.FACT, syntax: '(instance-name-to-symbol <instance-name-expression>)', description: 'Returns a symbol which is equivalent to its instance-name argument.' },
  { name: 'instances', category: CATEGORIES.FACT, syntax: '(instances [<module-name> [<class-name> [inherit]]])', description: 'Lists existing instances.' },
  { name: 'list-deffacts', category: CATEGORIES.FACT, syntax: '(list-deffacts [<module-name>])', description: 'Displays the names of all defined deffacts.' },
  { name: 'list-definstances', category: CATEGORIES.FACT, syntax: '(list-definstances [<module-name>])', description: 'Displays the names of all defined definstances.' },
  { name: 'load-facts', category: CATEGORIES.FACT, syntax: '(load-facts <file-name>)', description: 'Will read facts in text format from the file specified by the <file-name> argument and assert them.' },
  { name: 'load-instances', category: CATEGORIES.FACT, syntax: '(load-instances <file-name>)', description: 'Loads instances in text format from a file and creates them.' },
  { name: 'make-instance', category: CATEGORIES.FACT, syntax: '(make-instance <name-or-gensym> of <class> (<slot-name> <value>*)*)', description: 'Creates a new instance of a class with the given slot values.' },
  { name: 'message-duplicate-instance', category: CATEGORIES.FACT, syntax: '(message-duplicate-instance <instance> [to <instance-name>] <slot-override>*)', description: 'Uses the message-duplicate message to change the values of the instance.' },
  { name: 'message-modify-instance', category: CATEGORIES.FACT, syntax: '(message-modify-instance <instance> <slot-override>*)', description: 'Uses the message-modify message to change the values of the instance.' },
  { name: 'modify', category: CATEGORIES.FACT, syntax: '(modify <fact-index-or-address> (<slot-name> <value>*)+)', description: 'Replaces one or more slot values of a deftemplate fact, retracting and re-asserting it.' },
  { name: 'modify-instance', category: CATEGORIES.FACT, syntax: '(modify-instance <instance> (<slot-name> <value>*)+)', description: 'Replaces one or more slot values of an instance, sending the appropriate put- message(s).' },
  { name: 'ppdeffacts', category: CATEGORIES.FACT, syntax: '(ppdeffacts <deffacts-name> [<logical-name>])', description: 'Sends the source text of a deffacts to a logical name as output.' },
  { name: 'ppdefinstances', category: CATEGORIES.FACT, syntax: '(ppdefinstances <definstances-name> [<logical-name>])', description: 'Sends the source text of a definstances to a logical name as output.' },
  { name: 'ppinstance', category: CATEGORIES.FACT, syntax: '(ppinstance)', description: 'Directly prints the slots of the active instance and is the one used to implement the print handler attached to class USER.' },
  { name: 'restore-instances', category: CATEGORIES.FACT, syntax: '(restore-instances <file-name>)', description: 'Loads instances from a file into the CLIPS environment.' },
  { name: 'retract', category: CATEGORIES.FACT, syntax: '(retract <fact-index-or-address>+)', description: 'Removes one or more facts from the fact list.' },
  { name: 'save-facts', category: CATEGORIES.FACT, syntax: '(save-facts <file-name> [<save-scope> <deftemplate-names>*])', description: 'Saves all of the facts in the current fact-list into the file specified by the <file-name> argument.' },
  { name: 'save-instances', category: CATEGORIES.FACT, syntax: '(save-instances <file-name> [local | visible [[inherit] <class>+])', description: 'Saves all instances to a file in a text format that load-instances or restore-instances can read back, though module information is not preserved.' },
  { name: 'send', category: CATEGORIES.FACT, syntax: '(send <instance> <message-name> <argument>*)', description: 'Sends a message to an instance, invoking its message-handler(s) for that message.' },
  { name: 'set-fact-duplication', category: CATEGORIES.FACT, syntax: '(set-fact-duplication <boolean-expression>)', description: 'Sets fact duplication behavior.' },
  { name: 'str-assert', category: CATEGORIES.FACT, syntax: '(str-assert <string>)', description: 'Parses a string as a fact and asserts it, similar to assert-string.' },
  { name: 'symbol-to-instance-name', category: CATEGORIES.FACT, syntax: '(symbol-to-instance-name <symbol-expression>)', description: 'Returns an instance-name which is equivalent to its symbol argument.' },
  { name: 'undeffacts', category: CATEGORIES.FACT, syntax: '(undeffacts <deffacts-name>)', description: 'Deletes a previously defined deffacts.' },
  { name: 'undefinstances', category: CATEGORIES.FACT, syntax: '(undefinstances <definstances-name>)', description: 'Deletes a previously defined definstances.' },
  { name: 'unmake-instance', category: CATEGORIES.FACT, syntax: '(unmake-instance <instance>+)', description: 'Deletes one or more instances.' },

  // --- Miscellaneous ---
  { name: 'agenda', category: CATEGORIES.MISC, syntax: '(agenda [<module-name>])', description: 'Displays all activations on the agenda.' },
  { name: 'apropos', category: CATEGORIES.MISC, syntax: '(apropos <lexeme>)', description: 'Displays all symbols currently defined in CLIPS which contain a specified substring.' },
  { name: 'batch', category: CATEGORIES.MISC, syntax: '(batch <file-name>)', description: 'Allows automatic processing of CLIPS interactive commands by replacing standard input with the contents of a file.' },
  { name: 'batch*', category: CATEGORIES.MISC, syntax: '(batch* <file-name>)', description: 'Evaluates the series of commands stored in the file specified by the <file-name> argument.' },
  { name: 'bload', category: CATEGORIES.MISC, syntax: '(bload <file-name>)', description: 'Loads the precompiled constructs stored in the binary file specified by the <file-name> argument.' },
  { name: 'browse-classes', category: CATEGORIES.MISC, syntax: '(browse-classes [<class-name>])', description: 'Provides a rudimentary display of the inheritance relationships between a class and all its subclasses.' },
  { name: 'bsave', category: CATEGORIES.MISC, syntax: '(bsave <file-name>)', description: 'Writes all of the construct definitions currently loaded to the file specified by the <file-name> argument.' },
  { name: 'build', category: CATEGORIES.MISC, syntax: '(build <string-or-symbol>)', description: 'Parses and defines a construct (e.g. a defrule or deftemplate) from a string.' },
  { name: 'call-next-handler', category: CATEGORIES.MISC, syntax: '(call-next-handler)', description: 'Executes the next applicable (shadowed) message-handler from within the body of the current handler.' },
  { name: 'call-next-method', category: CATEGORIES.MISC, syntax: '(call-next-method)', description: 'Executes the next most specific (shadowed) method from within the body of the current method.' },
  { name: 'call-specific-method', category: CATEGORIES.MISC, syntax: '(call-specific-method <generic-function> <method-index> <expression>*)', description: 'Allows a particular method of a generic function to be called without regards to method precedence.' },
  { name: 'chdir', category: CATEGORIES.MISC, syntax: '(chdir [<path>])', description: 'Changes the current directory.' },
  { name: 'class', category: CATEGORIES.MISC, syntax: '(class <object-expression>)', description: 'Returns a symbol which is the name of the class of its argument.' },
  { name: 'class-abstractp', category: CATEGORIES.MISC, syntax: '(class-abstractp <class-name>)', description: 'Returns TRUE if the specified class is abstract (cannot have direct instances).' },
  { name: 'class-existp', category: CATEGORIES.MISC, syntax: '(class-existp <class-name>)', description: 'Returns the symbol TRUE if the specified class is defined; otherwise, it returns the symbol FALSE.' },
  { name: 'class-reactivep', category: CATEGORIES.MISC, syntax: '(class-reactivep <class-name>)', description: 'Returns TRUE if the specified class is reactive (its instances can match object patterns).' },
  { name: 'class-slots', category: CATEGORIES.MISC, syntax: '(class-slots <class-name> [inherit])', description: 'Returns a multifield value containing the names of the explicitly defined slots of the specified class.' },
  { name: 'class-subclasses', category: CATEGORIES.MISC, syntax: '(class-subclasses <class-name> [inherit])', description: 'Returns a multifield value containing the names of the direct subclasses of the specified class.' },
  { name: 'class-superclasses', category: CATEGORIES.MISC, syntax: '(class-superclasses <class-name> [inherit])', description: 'Returns a multifield value containing the names of the direct superclasses of the specified class.' },
  { name: 'clear', category: CATEGORIES.MISC, syntax: '(clear)', description: 'Removes all constructs and associated data (such as facts and instances).' },
  { name: 'clear-error', category: CATEGORIES.MISC, syntax: '(clear-error)', description: 'Resets the error state (or status value) to the the symbol FALSE and returns the prior value of the error state.' },
  { name: 'clear-focus-stack', category: CATEGORIES.MISC, syntax: '(clear-focus-stack)', description: 'Removes all module names from the focus stack.' },
  { name: 'conserve-mem', category: CATEGORIES.MISC, syntax: '(conserve-mem <value>)', description: 'Is used to enable or disable the storage of the text representation for constructs used by the save and pp<construct> commands.' },
  { name: 'constructs-to-c', category: CATEGORIES.MISC, syntax: '(constructs-to-c <file-name-prefix> <path> <max-files>)', description: 'Generates C source files representing the current constructs, for building CLIPS into a standalone executable.' },
  { name: 'defclass-module', category: CATEGORIES.MISC, syntax: '(defclass-module <defclass-name>)', description: 'Returns the module in which the specified defclass name is defined.' },
  { name: 'deffunction-module', category: CATEGORIES.MISC, syntax: '(deffunction-module <deffunction-name>)', description: 'Returns the module in which the specified deffunction name is defined.' },
  { name: 'defgeneric-module', category: CATEGORIES.MISC, syntax: '(defgeneric-module <defgeneric-name>)', description: 'Returns the module in which the specified defgeneric name is defined.' },
  { name: 'defglobal-module', category: CATEGORIES.MISC, syntax: '(defglobal-module <defglobal-name>)', description: 'Returns the module in which the specified defglobal name is defined.' },
  { name: 'defrule-module', category: CATEGORIES.MISC, syntax: '(defrule-module <defrule-name>)', description: 'Returns the module in which the specified defrule name is defined.' },
  { name: 'deftemplate-module', category: CATEGORIES.MISC, syntax: '(deftemplate-module <deftemplate-name>)', description: 'Returns the module in which the specified deftemplate name is defined.' },
  { name: 'dependencies', category: CATEGORIES.MISC, syntax: '(dependencies <fact-or-instance-specifier>)', description: 'Lists the partial matches from which a fact or instance receives logical support.' },
  { name: 'dependents', category: CATEGORIES.MISC, syntax: '(dependents <fact-or-instance-specifier>)', description: 'Lists all facts and instances which receive logical support from a fact or instance.' },
  { name: 'describe-class', category: CATEGORIES.MISC, syntax: '(describe-class <class-name>)', description: 'Prints a verbose description of a class: its role, superclasses/subclasses, precedence list, slots and facets, and message-handlers.' },
  { name: 'dribble-off', category: CATEGORIES.MISC, syntax: '(dribble-off)', description: 'Stops sending output to the dribble file and closes it.' },
  { name: 'dribble-on', category: CATEGORIES.MISC, syntax: '(dribble-on <file-name>)', description: 'Sends all output normally sent to the logical names stdout, werror, and wwarning to the file specified by the <file-name> argument as well as sending output to its normal destination.' },
  { name: 'dynamic-get', category: CATEGORIES.MISC, syntax: '(dynamic-get <slot-name-expression>)', description: 'Returns the value of the specified slot of the active instance.' },
  { name: 'dynamic-put', category: CATEGORIES.MISC, syntax: '(dynamic-put <slot-name-expression> <expression>*)', description: 'Sets the value of the specified slot of the active instance.' },
  { name: 'edit', category: CATEGORIES.MISC, syntax: '(edit [<construct-name>])', description: 'Opens the built-in line editor on a construct\'s definition (interactive CLIPS environments only).' },
  { name: 'eval', category: CATEGORIES.MISC, syntax: '(eval <string-or-symbol>)', description: 'Parses and evaluates a string or symbol as a CLIPS expression, returning its result.' },
  { name: 'exit', category: CATEGORIES.MISC, syntax: '(exit [<integer-expression>])', description: 'Terminates CLIPS execution.' },
  { name: 'fetch', category: CATEGORIES.MISC, syntax: '(fetch <file-name>)', description: 'Loads the named file into the internal lookup table.' },
  { name: 'focus', category: CATEGORIES.MISC, syntax: '(focus <module-name>+)', description: 'Pushes one or more modules onto the focus stack.' },
  { name: 'gensym*', category: CATEGORIES.MISC, syntax: '(gensym*)', description: 'Generates a symbol guaranteed not to collide with any existing symbol, fact, or instance name.' },
  { name: 'get', category: CATEGORIES.MISC, syntax: '(get <instance> <slot-name>)', description: 'Low-level retrieval of a slot\'s value; prefer the auto-generated get-<slot-name> message-handler.' },
  { name: 'get-current-module', category: CATEGORIES.MISC, syntax: '(get-current-module)', description: 'Returns the name of the current module.' },
  { name: 'get-defclass-list', category: CATEGORIES.MISC, syntax: '(get-defclass-list [<module-name>])', description: 'Returns a multifield value containing the names of all defclass constructs visible to the module specified by <module-name> or to the current module if none is specified.' },
  { name: 'get-deffunction-list', category: CATEGORIES.MISC, syntax: '(get-deffunction-list [<module-name>])', description: 'Returns a multifield value containing the names of all deffunction constructs visible to the module specified by <module-name> or to the current module if none is specified.' },
  { name: 'get-defgeneric-list', category: CATEGORIES.MISC, syntax: '(get-defgeneric-list)', description: 'Returns a multifield value containing the names of all defgeneric constructs that are currently defined.' },
  { name: 'get-defglobal-list', category: CATEGORIES.MISC, syntax: '(get-defglobal-list [<module-name>])', description: 'Returns a multifield value containing the names of all global variables visible to the module specified by <module-name> or to the current module if none is specified.' },
  { name: 'get-defmessage-handler-list', category: CATEGORIES.MISC, syntax: '(get-defmessage-handler-list <class-name> [inherit])', description: 'Returns a multifield value containing the class names, message names, and message types of the message-handlers attached directly to the specified class (implicit slot-accessors are not included).' },
  { name: 'get-defmethod-list', category: CATEGORIES.MISC, syntax: '(get-defmethod-list [<generic-function-name>])', description: 'Returns a multifield value containing method name/indices pairs for all defmethod constructs that are currently defined.' },
  { name: 'get-defmodule-list', category: CATEGORIES.MISC, syntax: '(get-defmodule-list)', description: 'Returns a multifield value containing the names of all defmodules that are currently defined.' },
  { name: 'get-defrule-list', category: CATEGORIES.MISC, syntax: '(get-defrule-list)', description: 'Returns a multifield value containing the names of all defrule constructs visible to the module specified by <module-name> or to the current module if none is specified.' },
  { name: 'get-deftemplate-list', category: CATEGORIES.MISC, syntax: '(get-deftemplate-list [<module-name>])', description: 'Returns a multifield value containing the names of all deftemplate constructs visible to the given module (or the current module if none is specified).' },
  { name: 'get-dynamic-constraint-checking', category: CATEGORIES.MISC, syntax: '(get-dynamic-constraint-checking)', description: 'Returns TRUE if runtime (dynamic) constraint checking of slot values is enabled.' },
  { name: 'get-error', category: CATEGORIES.MISC, syntax: '(get-error)', description: 'Returns the current value of the error state (or status value).' },
  { name: 'get-focus', category: CATEGORIES.MISC, syntax: '(get-focus)', description: 'Returns the module name of the current focus.' },
  { name: 'get-focus-stack', category: CATEGORIES.MISC, syntax: '(get-focus-stack)', description: 'Returns a multifield value containing all of the module names in the focus stack.' },
  { name: 'get-function-restrictions', category: CATEGORIES.MISC, syntax: '(get-function-restrictions <function-name>)', description: 'Can be used to gain access to the restriction string associated with a system or user defined function created using the AddUDF API.' },
  { name: 'get-method-restrictions', category: CATEGORIES.MISC, syntax: '(get-method-restrictions <generic-function> <method-index>)', description: 'Returns a multifield value describing the parameter restrictions of a method of a generic function.' },
  { name: 'get-reset-globals', category: CATEGORIES.MISC, syntax: '(get-reset-globals)', description: 'Returns the current value of the reset global variables behavior (either the symbol TRUE or FALSE).' },
  { name: 'get-salience-evaluation', category: CATEGORIES.MISC, syntax: '(get-salience-evaluation)', description: 'Returns the current salience evaluation behavior (either the symbol when-defined, when-activated, or every-cycle).' },
  { name: 'get-sequence-operator-recognition', category: CATEGORIES.MISC, syntax: '(get-sequence-operator-recognition)', description: 'Returns the current value of the sequence operator recognition behavior (either the symbol TRUE or FALSE).' },
  { name: 'get-strategy', category: CATEGORIES.MISC, syntax: '(get-strategy)', description: 'Returns the current conflict resolution strategy (either the symbol depth, breadth, simplicity, complexity, lex, mea, or random).' },
  { name: 'gm-time', category: CATEGORIES.MISC, syntax: '(gm-time)', description: 'Returns a multifield value with Greenwich Mean Time fields: year, month, day, hours, minutes, seconds, day of week, and a daylight-savings flag.' },
  { name: 'init-slots', category: CATEGORIES.MISC, syntax: '(init-slots)', description: 'Implements the init message-handler attached to the class USER.' },
  { name: 'instance-address', category: CATEGORIES.MISC, syntax: '(instance-address [<module> | *] <instance-expression>)', description: 'Returns the address of its instance argument.' },
  { name: 'instance-name', category: CATEGORIES.MISC, syntax: '(instance-name <instance-expression>)', description: 'Returns a symbol which is the name of its instance argument.' },
  { name: 'list-defclasses', category: CATEGORIES.MISC, syntax: '(list-defclasses [<module-name>])', description: 'Displays the names of all defined defclasses.' },
  { name: 'list-deffunctions', category: CATEGORIES.MISC, syntax: '(list-deffunctions)', description: 'Displays the names of all defined deffunctions.' },
  { name: 'list-defgenerics', category: CATEGORIES.MISC, syntax: '(list-defgenerics [<module-name>])', description: 'Displays the names of all defined generic functions.' },
  { name: 'list-defglobals', category: CATEGORIES.MISC, syntax: '(list-defglobals [<module-name>])', description: 'Displays the names of all defined defglobals.' },
  { name: 'list-defmessage-handlers', category: CATEGORIES.MISC, syntax: '(list-defmessage-handlers [<class-name> [inherit]])', description: 'Displays the names of defined defmessage-handlers.' },
  { name: 'list-defmethods', category: CATEGORIES.MISC, syntax: '(list-defmethods [<generic-function-name>])', description: 'Displays the names, arguments, and indices of all defined defmethods.' },
  { name: 'list-defmodules', category: CATEGORIES.MISC, syntax: '(list-defmodules)', description: 'Displays the names of all defined defmodule constructs.' },
  { name: 'list-defrules', category: CATEGORIES.MISC, syntax: '(list-defrules [<module-name>])', description: 'Displays the names of all defined defrules.' },
  { name: 'list-deftemplates', category: CATEGORIES.MISC, syntax: '(list-deftemplates [<module-name>])', description: 'Displays the names of all deftemplates.' },
  { name: 'list-focus-stack', category: CATEGORIES.MISC, syntax: '(list-focus-stack)', description: 'Lists all module names on the focus stack.' },
  { name: 'list-watch-items', category: CATEGORIES.MISC, syntax: '(list-watch-items [<watch-item>])', description: 'Displays the current state of watch items.' },
  { name: 'load', category: CATEGORIES.MISC, syntax: '(load <file-name>)', description: 'Compiles the construct definitions stored in the file specified by the <file-name> argument.' },
  { name: 'load*', category: CATEGORIES.MISC, syntax: '(load* <file-name>)', description: 'Like load, but compiles the file\'s constructs without printing progress messages.' },
  { name: 'local-time', category: CATEGORIES.MISC, syntax: '(local-time)', description: 'Returns a multifield value containing fields indicating the local time.' },
  { name: 'matches', category: CATEGORIES.MISC, syntax: '(matches <rule-name> [<verbosity>])', description: 'Displays (or returns counts of) the facts/instances matching each pattern, partial matches, and activations for a rule.' },
  { name: 'mem-requests', category: CATEGORIES.MISC, syntax: '(mem-requests)', description: 'Returns an integer representing the number of outstanding memory requests CLIPS has made from the operating system.' },
  { name: 'mem-used', category: CATEGORIES.MISC, syntax: '(mem-used)', description: 'Returns an integer representing the number of bytes CLIPS has currently in-use or cached for later use.' },
  { name: 'message-handler-existp', category: CATEGORIES.MISC, syntax: '(message-handler-existp <class-name> <handler-name> [<handler-type>])', description: 'Returns the symbol TRUE if the specified message-handler is defined (directly only, not by inheritance) for the class; otherwise, it returns the symbol FALSE.' },
  { name: 'operating-system', category: CATEGORIES.MISC, syntax: '(operating-system)', description: 'Returns a symbol indicating the operating system CLIPS is running on.' },
  { name: 'options', category: CATEGORIES.MISC, syntax: '(options)', description: 'Prints the compiler flag settings (for enabling/disabling various features) used for creating the CLIPS executable.' },
  { name: 'override-next-handler', category: CATEGORIES.MISC, syntax: '(override-next-handler <expression>*)', description: 'Is identical to call-next-handler except that it can change the arguments passed to the shadowed handler.' },
  { name: 'override-next-method', category: CATEGORIES.MISC, syntax: '(override-next-method <expression>*)', description: 'Is similar to call-next-method, except that new arguments can be provided.' },
  { name: 'pop-focus', category: CATEGORIES.MISC, syntax: '(pop-focus)', description: 'Removes the current focus from the focus stack and returns the module name of the current focus.' },
  { name: 'ppdefclass', category: CATEGORIES.MISC, syntax: '(ppdefclass <class-name> [<logical-name>])', description: 'Sends the source text of a defclass to a logical name as output.' },
  { name: 'ppdeffunction', category: CATEGORIES.MISC, syntax: '(ppdeffunction <deffunction-name> [<logical-name>])', description: 'Sends the source text of a deffunction to a logical name as output.' },
  { name: 'ppdefgeneric', category: CATEGORIES.MISC, syntax: '(ppdefgeneric <generic-function-name> [<logical-name>])', description: 'Sends the source text of a defgeneric to a logical name as output.' },
  { name: 'ppdefglobal', category: CATEGORIES.MISC, syntax: '(ppdefglobal <global-variable-name> [<logical-name>])', description: 'Sends the source text of a defglobal to a logical name as output.' },
  { name: 'ppdefmessage-handler', category: CATEGORIES.MISC, syntax: '(ppdefmessage-handler <class-name> <handler-name> [<handler-type> [<logical-name>]])', description: 'Sends the source text of a defmessage-handler to a logical name as output.' },
  { name: 'ppdefmethod', category: CATEGORIES.MISC, syntax: '(ppdefmethod <generic-function-name> <index> [<logical-name>])', description: 'Sends the source text of a defmethod to a logical name as output.' },
  { name: 'ppdefmodule', category: CATEGORIES.MISC, syntax: '(ppdefmodule <defmodule-name> [<logical-name>])', description: 'Sends the source text of a defmodule to a logical name as output.' },
  { name: 'ppdefrule', category: CATEGORIES.MISC, syntax: '(ppdefrule <rule-name> [<logical-name>])', description: 'Sends the source text of a defrule to a logical name as output.' },
  { name: 'ppdeftemplate', category: CATEGORIES.MISC, syntax: '(ppdeftemplate <deftemplate-name> [<logical-name>])', description: 'Sends the source text of a deftemplate to a logical name as output.' },
  { name: 'preview-generic', category: CATEGORIES.MISC, syntax: '(preview-generic <generic-function-name> <expression>*)', description: 'Lists all applicable methods for a particular generic function call in order of decreasing precedence.' },
  { name: 'preview-send', category: CATEGORIES.MISC, syntax: '(preview-send <class-name> <message-name>)', description: 'Displays a list of all the applicable message-handlers for a message sent to an instance of a particular class.' },
  { name: 'primitives-info', category: CATEGORIES.MISC, syntax: '(primitives-info)', description: 'Prints internal diagnostic information about CLIPS\'s primitive data type usage.' },
  { name: 'print-region', category: CATEGORIES.MISC, syntax: '(print-region <logical-name> <file-name> <topic-field>*)', description: 'Looks up a specified entry in a particular file which has been loaded previously into the lookup table and prints the contents of that entry to the specified output.' },
  { name: 'put', category: CATEGORIES.MISC, syntax: '(put <instance> <slot-name> <expression>*)', description: 'Low-level assignment of a slot\'s value; prefer the auto-generated put-<slot-name> message-handler.' },
  { name: 'random', category: CATEGORIES.MISC, syntax: '(random [<begin> <end>])', description: 'Returns a random integer, optionally bounded between the given begin and end values, inclusive.' },
  { name: 'refresh', category: CATEGORIES.MISC, syntax: '(refresh <rule-name>)', description: 'Places all current activations of the specified defrule on the agenda.' },
  { name: 'refresh-agenda', category: CATEGORIES.MISC, syntax: '(refresh-agenda [<module-name>])', description: 'Reevaluates the saliences of all rules on the agenda regardless of the current salience evaluation setting.' },
  { name: 'release-mem', category: CATEGORIES.MISC, syntax: '(release-mem)', description: 'Releases all free memory cached by CLIPS back to the operating system.' },
  { name: 'remove-break', category: CATEGORIES.MISC, syntax: '(remove-break [<defrule-name>])', description: 'Removes a breakpoint for the specified defrule.' },
  { name: 'reset', category: CATEGORIES.MISC, syntax: '(reset)', description: 'Removes all activations and facts, deletes all instances, resets global variables, re-asserts deffacts, and re-creates definstances.' },
  { name: 'rewind', category: CATEGORIES.MISC, syntax: '(rewind <logical-name>)', description: 'Sets the position in a file stream previously opened with the open command to the beginning of the file.' },
  { name: 'rule-complexity', category: CATEGORIES.MISC, syntax: '(rule-complexity <rule-name>)', description: 'Returns an integer indicating the pattern-matching complexity of a rule\'s LHS.' },
  { name: 'rules', category: CATEGORIES.MISC, syntax: '(rules)', description: 'Prints the names of all defrules visible in the current module and their total count.' },
  { name: 'run', category: CATEGORIES.MISC, syntax: '(run [<integer-expression>])', description: 'Starts execution of activated rules.' },
  { name: 'save', category: CATEGORIES.MISC, syntax: '(save <file-name>)', description: 'Writes all construct definitions to the file specified by the <file-name> argument, overwriting the file if it already exists.' },
  { name: 'seed', category: CATEGORIES.MISC, syntax: '(seed <integer>)', description: 'Seeds the random number generator.' },
  { name: 'seek', category: CATEGORIES.MISC, syntax: '(seek <logical-name> <offset> <relative-position)', description: 'Sets the current position in a file stream previously opened with the open command.' },
  { name: 'set-break', category: CATEGORIES.MISC, syntax: '(set-break <rule-name>)', description: 'Sets a breakpoint for the specified defrule.' },
  { name: 'set-current-module', category: CATEGORIES.MISC, syntax: '(set-current-module <defmodule-name>)', description: 'Sets the current module.' },
  { name: 'set-dynamic-constraint-checking', category: CATEGORIES.MISC, syntax: '(set-dynamic-constraint-checking <boolean-expression>)', description: 'Sets the dynamic constraint checking behavior.' },
  { name: 'set-error', category: CATEGORIES.MISC, syntax: '(set-error <expression>)', description: 'Sets the error state (or status value).' },
  { name: 'set-reset-globals', category: CATEGORIES.MISC, syntax: '(set-reset-globals <boolean-expression>)', description: 'Sets the values of the reset globals behavior.' },
  { name: 'set-salience-evaluation', category: CATEGORIES.MISC, syntax: '(set-salience-evaluation <evaluation>)', description: 'Sets the salience evaluation behavior.' },
  { name: 'set-sequence-operator-recognition', category: CATEGORIES.MISC, syntax: '(set-sequence-operator-recognition <boolean-expression>)', description: 'Sets the sequence operator recognition behavior.' },
  { name: 'setgen', category: CATEGORIES.MISC, syntax: '(setgen <integer-expression>)', description: 'Assigns the starting integer used by the gensym and gensym* functions.' },
  { name: 'show-breaks', category: CATEGORIES.MISC, syntax: '(show-breaks [<module-name>])', description: 'Displays all the rules which have breakpoints set.' },
  { name: 'show-defglobals', category: CATEGORIES.MISC, syntax: '(show-defglobals [<module-name>])', description: 'Displays the name and current value of all defglobals.' },
  { name: 'show-fht', category: CATEGORIES.MISC, syntax: '(show-fht)', description: 'Displays diagnostic statistics about the internal fact hash table.' },
  { name: 'show-fpn', category: CATEGORIES.MISC, syntax: '(show-fpn)', description: 'Displays diagnostic information about the internal fact pattern (Rete) network.' },
  { name: 'show-joins', category: CATEGORIES.MISC, syntax: '(show-joins [<rule-name>])', description: 'Displays diagnostic information about the join network nodes used to match rule patterns.' },
  { name: 'show-opn', category: CATEGORIES.MISC, syntax: '(show-opn)', description: 'Displays diagnostic information about the internal object pattern network.' },
  { name: 'slot-allowed-values', category: CATEGORIES.MISC, syntax: '(slot-allowed-values <class-name> <slot-name>)', description: 'Returns a multifield value containing the allowed values for a slot (specified in any of allowed-… facets for the slots).' },
  { name: 'slot-cardinality', category: CATEGORIES.MISC, syntax: '(slot-cardinality <class-name> <slot-name>)', description: 'Returns a multifield value containing the minimum and maximum cardinality allowed for a multifield slot of the specified class.' },
  { name: 'slot-delete$', category: CATEGORIES.MISC, syntax: '(slot-delete$ <instance> <mv-slot-name> <range-begin> <range-end>)', description: 'Deletes a range of values from a multifield slot via a put- message, without needing a get- message first.' },
  { name: 'slot-direct-accessp', category: CATEGORIES.MISC, syntax: '(slot-direct-accessp <class-expression> <slot-name-expression>)', description: 'Returns the symbol TRUE if the specified slot in the specified class can be accessed directly; otherwise, it returns the symbol FALSE.' },
  { name: 'slot-direct-delete$', category: CATEGORIES.MISC, syntax: '(slot-direct-delete$ <mv-slot-name> <range-begin> <range-end>)', description: 'Directly deletes a range of values from a multifield slot without going through a put- message-handler.' },
  { name: 'slot-direct-insert$', category: CATEGORIES.MISC, syntax: '(slot-direct-insert$ <mv-slot-name> <index> <expression>+)', description: 'Directly inserts values into a multifield slot at a position, without going through a put- message-handler.' },
  { name: 'slot-direct-replace$', category: CATEGORIES.MISC, syntax: '(slot-direct-replace$ <mv-slot-name> <range-begin> <range-end> <expression>+)', description: 'Directly replaces a range of values in a multifield slot, without going through a put- message-handler.' },
  { name: 'slot-existp', category: CATEGORIES.MISC, syntax: '(slot-existp <class> <slot> [inherit])', description: 'Returns the symbol TRUE if the specified slot is present in the specified class; otherwise, it returns the symbol FALSE.' },
  { name: 'slot-facets', category: CATEGORIES.MISC, syntax: '(slot-facets <class-name> <slot-name>)', description: 'Returns a multifield value containing the facet values for the specified slot (the slot can be inherited or explicitly defined for the class).' },
  { name: 'slot-initablep', category: CATEGORIES.MISC, syntax: '(slot-initablep <class-expression> <slot-name-expression>)', description: 'Returns the symbol TRUE if the specified slot in the specified class is initializable; otherwise, it returns the symbol FALSE.' },
  { name: 'slot-insert$', category: CATEGORIES.MISC, syntax: '(slot-insert$ <instance> <mv-slot-name> <index> <expression>+)', description: 'Inserts values into a multifield slot at a position via a put- message, without needing a get- message first.' },
  { name: 'slot-publicp', category: CATEGORIES.MISC, syntax: '(slot-publicp <class-expression> <slot-name-expression>)', description: 'Returns the symbol TRUE if the specified slot in the specified class is public; otherwise, it returns the symbol FALSE.' },
  { name: 'slot-range', category: CATEGORIES.MISC, syntax: '(slot-range <class-name> <slot-name>)', description: 'Returns a multifield value containing the minimum and maximum numeric ranges allowed a slot.' },
  { name: 'slot-replace$', category: CATEGORIES.MISC, syntax: '(slot-replace$ <instance> <mv-slot-name> <range-begin> <range-end> <expression>+)', description: 'Replaces a range of values in a multifield slot via a put- message, without needing a get- message first.' },
  { name: 'slot-sources', category: CATEGORIES.MISC, syntax: '(slot-sources <class-name> <slot-name>)', description: 'Returns a multifield value containing the names of the classes which provide facets for a slot of the specified class.' },
  { name: 'slot-types', category: CATEGORIES.MISC, syntax: '(slot-types <class-name> <slot-name>)', description: 'Returns a multifield value containing the names of the primitive types allowed for a slot.' },
  { name: 'slot-writablep', category: CATEGORIES.MISC, syntax: '(slot-writablep <class-expression> <slot-name-expression>)', description: 'Returns the symbol TRUE if the specified slot in the specified class is writable; otherwise, it returns the symbol FALSE.' },
  { name: 'subclassp', category: CATEGORIES.MISC, syntax: '(subclassp <class1-name> <class2-name>)', description: 'Returns the symbol TRUE if the first class is a subclass of the second class; otherwise, it returns the symbol FALSE.' },
  { name: 'superclassp', category: CATEGORIES.MISC, syntax: '(superclassp <class1-name> <class2-name>)', description: 'Returns the symbol TRUE if the first class is a superclass of the second class; otherwise, it returns the symbol FALSE.' },
  { name: 'system', category: CATEGORIES.MISC, syntax: '(system <lexeme-expression>*)', description: 'Allows a call to the operating system.' },
  { name: 'tell', category: CATEGORIES.MISC, syntax: '(tell <logical-name>)', description: 'Returns the current position in a file stream previously opened with the open command.' },
  { name: 'time', category: CATEGORIES.MISC, syntax: '(time)', description: 'Returns a float representing the number of seconds elapsed since a fixed system reference time.' },
  { name: 'toss', category: CATEGORIES.MISC, syntax: '(toss <file-name>)', description: 'Unloads the named file from the internal lookup table and releases the memory back to the system.' },
  { name: 'type', category: CATEGORIES.MISC, syntax: '(type <expression>)', description: 'Returns a symbol which is the name of the type (or class) of its argument.' },
  { name: 'undefclass', category: CATEGORIES.MISC, syntax: '(undefclass <class-name>)', description: 'Deletes a previously defined defclass and all its subclasses.' },
  { name: 'undeffunction', category: CATEGORIES.MISC, syntax: '(undeffunction <deffunction-name>)', description: 'Deletes a previously defined deffunction.' },
  { name: 'undefgeneric', category: CATEGORIES.MISC, syntax: '(undefgeneric <generic-function-name>)', description: 'Deletes a previously defined generic function.' },
  { name: 'undefglobal', category: CATEGORIES.MISC, syntax: '(undefglobal <defglobal-name>)', description: 'Deletes a previously defined defglobal.' },
  { name: 'undefmessage-handler', category: CATEGORIES.MISC, syntax: '(undefmessage-handler <class-name> <handler-name> [<handler-type>])', description: 'Deletes a previously defined message-handler.' },
  { name: 'undefmethod', category: CATEGORIES.MISC, syntax: '(undefmethod <generic-function-name> <index>)', description: 'Deletes a previously defined generic function method.' },
  { name: 'undefrule', category: CATEGORIES.MISC, syntax: '(undefrule <defrule-name>)', description: 'Deletes a previously defined defrule.' },
  { name: 'undeftemplate', category: CATEGORIES.MISC, syntax: '(undeftemplate <deftemplate-name>)', description: 'Deletes a previously defined deftemplate.' },
  { name: 'unwatch', category: CATEGORIES.MISC, syntax: '(unwatch <watch-item>)', description: 'Disables the effect of the watch command for the specified watch item.' },
  { name: 'void', category: CATEGORIES.MISC, syntax: '(void)', description: 'Returns the void value.' },
  { name: 'watch', category: CATEGORIES.MISC, syntax: '(watch <watch-item>)', description: 'Enables debugging/informational output for various CLIPS operations (e.g. facts, rules, activations).' },
];

const BY_NAME = new Map(BUILTINS.map((entry) => [entry.name, entry]));

function getBuiltin(name) {
  return BY_NAME.get(name);
}

module.exports = { BUILTINS, CATEGORIES, getBuiltin };
